use_frameworks!

platform :ios, '10.0'

target 'SparkRouter_Example' do
  pod 'SparkRouter', :path => '../'

  target 'SparkRouter_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
